# Generated by Django 5.1.1 on 2024-10-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_gender_student_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='static/img/placeholder.png', upload_to=''),
        ),
    ]
