# Generated by Django 5.1.1 on 2024-10-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='static/media/placeholder.png', upload_to=''),
        ),
    ]
